module

public import HypoellipticAleksandrov.Statements.BellmanExponentWellDefined
public import HypoellipticAleksandrov.Statements.GreenDensityFullCoefficient
public import HypoellipticAleksandrov.Statements.HolderAutonomous
public import HypoellipticAleksandrov.Statements.HolderFullCoefficient
public import HypoellipticAleksandrov.Statements.HolderTimeVelocity
public import HypoellipticAleksandrov.Statements.HormanderHypoellipticity
public import HypoellipticAleksandrov.Statements.KineticAleksandrovAutonomous
public import HypoellipticAleksandrov.Statements.KineticAleksandrovAutonomousLocalised
public import HypoellipticAleksandrov.Statements.KineticAleksandrovCounterexample
public import HypoellipticAleksandrov.Statements.KineticAleksandrovFullCoefficient
public import HypoellipticAleksandrov.Statements.KineticAleksandrovTimeVelocity
public import HypoellipticAleksandrov.Statements.KineticAleksandrovTimeVelocityLocalised
public import HypoellipticAleksandrov.Statements.KineticGrowthLemma
public import HypoellipticAleksandrov.Statements.KineticHolder
public import HypoellipticAleksandrov.Statements.KineticInkSpots
public import HypoellipticAleksandrov.Statements.LiebermanDirichlet
public import HypoellipticAleksandrov.Statements.ParabolicAleksandrov
public import HypoellipticAleksandrov.Statements.ParabolicHarnack
public import HypoellipticAleksandrov.Statements.TerminalEvolution

/-! # The main theorems of the formalization -/
