module

public import Mathlib.Geometry.Manifold.VectorField.LieBracket
public import Mathlib.MeasureTheory.Integral.Bochner.Set
public import Mathlib.MeasureTheory.Function.LocallyIntegrable
public import Mathlib.MeasureTheory.Measure.Haar.NormedSpace
public import Mathlib.Topology.Algebra.Support
public import PDEFoundation.Ambient.Basic
public import PDEFoundation.Ambient.Basis

/-!
# Hörmander weak-equation carriers

This module records the transparent bracket and formal-adjoint carriers used
by the locally integrable Hörmander hypoellipticity input.  Smoothness is
always stated on the open carrier; no ellipticity or boundary assumptions are
introduced here.
-/

@[expose] public section

noncomputable section
set_option autoImplicit false

open Set MeasureTheory
open scoped BigOperators

namespace HypoellipticAleksandrov.KineticAleksandrov

/-- An iterated Lie word in the drift and squared vector-field generators. -/
inductive LieWord (k : ℕ) where
  | generator : Fin (k + 1) → LieWord k
  | bracket : LieWord k → LieWord k → LieWord k

/-- Evaluation of a Lie word as a vector field on Euclidean space. -/
def LieWord.eval {k N : ℕ}
    (X : Fin (k + 1) → PDE.Vec N → PDE.Vec N) :
    LieWord k → PDE.Vec N → PDE.Vec N
  | .generator i => X i
  | .bracket p q =>
      VectorField.lieBracket ℝ (LieWord.eval X p)
        (LieWord.eval X q)

/-- The Lie words generated by `X` span every tangent direction on `Ω`. -/
def LieAlgebraSpansOn {k N : ℕ} (Ω : Set (PDE.Vec N))
    (X : Fin (k + 1) → PDE.Vec N → PDE.Vec N) : Prop :=
  ∀ x ∈ Ω,
    Submodule.span ℝ
      (Set.range (fun w : LieWord k => LieWord.eval X w x)) = ⊤

/-- The Euclidean divergence of a vector field, in the canonical coordinates. -/
def euclideanDivergence {N : ℕ} (V : PDE.Vec N → PDE.Vec N)
    (x : PDE.Vec N) : ℝ :=
  ∑ i : Fin N, (fderiv ℝ V x (PDE.basisVec i)) i

/-- The formal adjoint applied to a smooth compactly supported test function. -/
def hormanderAdjointTest {k N : ℕ}
    (X : Fin (k + 1) → PDE.Vec N → PDE.Vec N)
    (c : PDE.Vec N → ℝ) (φ : PDE.Vec N → ℝ)
    (x : PDE.Vec N) : ℝ :=
  -euclideanDivergence (fun y => φ y • X 0 y) x +
    ∑ i : Fin k,
      euclideanDivergence
        (fun y =>
          euclideanDivergence (fun q => φ q • X i.succ q) y • X i.succ y)
        x +
    c x * φ x

/-- A locally integrable function satisfying the literal weak Hörmander equation. -/
def HasWeakHormanderEquation {k N : ℕ} (Ω : Set (PDE.Vec N))
    (X : Fin (k + 1) → PDE.Vec N → PDE.Vec N)
    (c g u : PDE.Vec N → ℝ) : Prop :=
  LocallyIntegrableOn u Ω volume ∧
    ContDiffOn ℝ (⊤ : ℕ∞) g Ω ∧
    ∀ φ : PDE.Vec N → ℝ,
      ContDiff ℝ (⊤ : ℕ∞) φ →
      HasCompactSupport φ →
      tsupport φ ⊆ Ω →
      (∫ x in Ω, u x * hormanderAdjointTest X c φ x) =
        ∫ x in Ω, g x * φ x

end HypoellipticAleksandrov.KineticAleksandrov
