module

public import HypoellipticAleksandrov.KineticAleksandrov.Evolution.BracketFields

/-!
# Spanning for the regularised operator `L_ε`

For `ε > 0` the Lie algebra generated by `X_0, X_1, …, X_d, Y_1, …, Y_d` already spans at
every point of `ℝ^{1+2d}` by the generators themselves (no commutator is needed): the `X_i`
span the velocity block because `β` is invertible, the `Y_l = √ε ∂_{z_l}` span the transported
block, and `X_0` has time component `1` (Proposition 2.1).

This module also records the block-spanning lemmas shared with the `ε = 0` bracket check.
-/

@[expose] public section

noncomputable section
set_option autoImplicit false

open scoped MatrixOrder

namespace HypoellipticAleksandrov.KineticAleksandrov.Evolution

variable {n : ℕ}

/-- A subspace containing the three coordinate blocks of `ℝ^{1+2d}` is everything. -/
theorem eq_top_of_blocks {W : Submodule ℝ (EvolutionVec n)}
    (ht : packPoint 1 0 0 ∈ W) (hv : ∀ u, packPoint 0 u 0 ∈ W)
    (hz : ∀ w, packPoint 0 0 w ∈ W) : W = ⊤ := by
  rw [eq_top_iff]
  intro y _
  have h : y = packPoint (timeCoord n y) 0 0 + packPoint 0 (diffusedCoord n y) 0 +
      packPoint 0 0 (transportedCoord n y) := by
    conv_lhs => rw [← packPoint_coords y]
    exact packPoint_eq_add _ _ _
  have hs : packPoint (timeCoord n y) 0 0 ∈ W := by
    have := W.smul_mem (timeCoord n y) ht
    have e : (timeCoord n y) • packPoint (1 : ℝ) (0 : PDE.Vec n) (0 : PDE.Vec n) =
        packPoint (timeCoord n y) 0 0 := by
      rw [← packPoint_smul]
      simp
    rwa [e] at this
  rw [h]
  exact W.add_mem (W.add_mem hs (hv _)) (hz _)

/-- The positive square root `β(x)` of the coefficient matrix is positive definite. -/
theorem posDef_sqrtCoeffAt {lam Lam : ℝ} {B : FullKineticCoefficient n}
    (hlam : 0 < lam) (hell : HasEverywhereLoewnerBounds lam Lam B) (x : EvolutionVec n) :
    (sqrtCoeffAt B x).PosDef :=
  posDef_sqrt (posDef_of_smul_one_le hlam (hell _ _ _).1)

/-- The rows of an invertible (positive-definite) matrix span `ℝ^d`. -/
theorem exists_row_combination {β : PDE.Mat n} (hβ : β.PosDef) (u : PDE.Vec n) :
    ∃ a : PDE.Vec n, ∀ j, ∑ i, a i * β i j = u j := by
  have hu : IsUnit β.det := (Matrix.isUnit_iff_isUnit_det β).1 hβ.isUnit
  refine ⟨Matrix.vecMul u β⁻¹, fun j => ?_⟩
  have h : Matrix.vecMul (Matrix.vecMul u β⁻¹) β = u := by
    rw [Matrix.vecMul_vecMul, Matrix.nonsing_inv_mul β hu, Matrix.vecMul_one]
  have := congrFun h j
  simpa [Matrix.vecMul, dotProduct] using this

/-- If all `X_i(x)` lie in `W` and `β(x)` is invertible, the whole velocity block lies in `W`. -/
theorem packPoint_diffused_mem {B : FullKineticCoefficient n} {x : EvolutionVec n}
    (hβ : (sqrtCoeffAt B x).PosDef) {W : Submodule ℝ (EvolutionVec n)}
    (hX : ∀ i, diffusionField B i x ∈ W) (u : PDE.Vec n) : packPoint 0 u 0 ∈ W := by
  obtain ⟨a, ha⟩ := exists_row_combination hβ u
  have e : packPoint 0 u 0 = ∑ i, a i • diffusionField B i x := by
    refine ext_coords ?_ ?_ ?_
    · simp [diffusionField, map_sum]
    · simp only [diffusionField, map_sum, map_smul, diffusedCoord_packPoint]
      ext j
      simp [Finset.sum_apply, ha j]
    · simp [diffusionField, map_sum]
  rw [e]
  exact W.sum_mem fun i _ => W.smul_mem _ (hX i)

/-- The `ε > 0` regularising fields fill the transported block. -/
theorem packPoint_transported_mem_of_regularizing {ε : ℝ} (hε : 0 < ε) {x : EvolutionVec n}
    {W : Submodule ℝ (EvolutionVec n)} (hY : ∀ l, regularizingField ε l x ∈ W)
    (w : PDE.Vec n) : packPoint 0 0 w ∈ W := by
  have hs : Real.sqrt ε ≠ 0 := (Real.sqrt_pos.2 hε).ne'
  have e : packPoint 0 0 w = ∑ l, (w l / Real.sqrt ε) • regularizingField ε l x := by
    refine ext_coords ?_ ?_ ?_
    · simp [regularizingField, map_sum]
    · simp [regularizingField, map_sum]
    · simp only [regularizingField, map_sum, map_smul, transportedCoord_packPoint]
      funext j
      simp [Finset.sum_apply, Pi.single_apply]
      field_simp
  rw [e]
  exact W.sum_mem fun l _ => W.smul_mem _ (hY l)

/-- **Bracket (spanning) condition for `L_ε`, `ε > 0`.**  The Lie algebra generated by
`X_0, X_i, Y_l` spans `ℝ^{1+2d}` at every point; in fact the generators themselves span. -/
theorem lieAlgebraSpansOn_regularizedFields {lam Lam ε : ℝ} {B : FullKineticCoefficient n}
    {b : PDE.Vec n → PDE.Vec n} (hlam : 0 < lam) (hell : HasEverywhereLoewnerBounds lam Lam B)
    (hε : 0 < ε) :
    LieAlgebraSpansOn (Set.univ : Set (EvolutionVec n)) (regularizedFields B b ε) := by
  intro x _
  set W := Submodule.span ℝ
    (Set.range (fun w : LieWord (n + n) => LieWord.eval (regularizedFields B b ε) w x)) with hW
  have hgen : ∀ i, regularizedFields B b ε i x ∈ W := fun i =>
    Submodule.subset_span ⟨LieWord.generator i, rfl⟩
  have hX : ∀ i, diffusionField B i x ∈ W := fun i => by
    have := hgen (Fin.succ (Fin.castAdd n i))
    simpa only [regularizedFields, Fin.cons_succ, Fin.append_left] using this
  have hY : ∀ l, regularizingField ε l x ∈ W := fun l => by
    have := hgen (Fin.succ (Fin.natAdd n l))
    simpa only [regularizedFields, Fin.cons_succ, Fin.append_right] using this
  have h0 : driftField B b x ∈ W := by
    simpa only [regularizedFields, Fin.cons_zero] using hgen 0
  have hv := packPoint_diffused_mem (posDef_sqrtCoeffAt hlam hell x) hX
  have hz := packPoint_transported_mem_of_regularizing hε (x := x) hY
  refine eq_top_of_blocks ?_ hv hz
  have e : packPoint 1 0 0 = driftField B b x -
      packPoint 0 (fun k => - driftCorrection B k x) 0 - packPoint 0 0 (b (diffusedCoord n x)) := by
    refine ext_coords ?_ ?_ ?_ <;> simp [driftField]
  rw [e]
  exact W.sub_mem (W.sub_mem h0 (hv _)) (hz _)

end HypoellipticAleksandrov.KineticAleksandrov.Evolution
